spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devis
    username: postgres
    password: 2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
server:
  port: 8081

app:
  file:
    upload-dir: ./uploads
  pdf:
    generation:
      batch-delay: 120000

