spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devis
    username: postgres
    password: 2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false
server:
  port: 8081

pdf:
  storage:
    path: ./devis-pdf
  base-url: http://localhost:8081/pdf/
