spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devis
    username: postgres
    password: 2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/chakir-realm
          jwk-set-uri: http://localhost:8090/realms/chakir-realm/protocol/openid-connect/certs
app:
  file:
    upload-dir: ./uploads
  pdf:
    generation:
      batch-delay: 120000

keycloak:
  realm: chakir-realm
  auth-server-url: http://localhost:8090
  resource: devis-app
  public-client: true
  principal-attribute: preferred_username
  credentials:
    secret: M8PHJWprnfpkLX47a2jQ030emPl7dFV2


